services:
  pocketbase:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - pb_data:/pb/pb_data
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - PB_S3_ENDPOINT=https://a4cfe5819f278c8c5d8fd6b5dcffc8ce.r2.cloudflarestorage.com
      - PB_S3_BUCKET=arqonlabs-assii-diplomados
      - PB_S3_REGION=auto
      - PB_S3_ACCESS_KEY=7460268d0899d188e34f63e6f6261cd1
      - PB_S3_SECRET_KEY=7663c7a427d4b967f360825569f9c0083daebbff27086ce49a5733faa64ccb1d
      - PB_S3_FORCE_PATH_STYLE=true
    restart: unless-stopped

volumes:
  pb_data:
